## Snakemake configuration file

## Directory where the read data are stored, recommend absolute directory
bam_dir: yourbamfiles/

## Cell type you want to name:
celltype: 'DN'

## If your bam files already have been sorted and removed of duplicated reads, 
## provide the directory in the following parameter instead
## otherwise, don't change it
cleanbam_dir: cleanbam/

## macs2 peakcalling parameters:
## you need to provide the path of your executable macs2 tool
macs2_params:
        dir: yourpath/macs2
        fdr: 0.01
        small_length: 1000
        large_length: 10000

sort_params:
  ncpus: 10

